# Generated by Django 4.0 on 2021-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destinations_stars_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='Stars_Hotel',
            field=models.CharField(choices=[('5 Stars Hotel', '5 Star'), ('4 Stars Hotel', '4 Star'), ('3 Stars Hotel', '3 Star'), ('2 Stars Hotel', '2 Star'), ('1 Stars Hotel', '1 Star'), ('0 Stars Hotel', '0 Star')], default='Five Star', max_length=32),
        ),
    ]
